_target_: src.models.ImageCaptionModule

defaults:
  - net: inception_rnn

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

dataset_dir: ${paths.data_dir}/${data.dataset_name}
