_target_: src.models.components.ImageCaptionNet
image_embed_net:
  _target_: src.models.components.image_embedding.InceptionNet
  drop_rate: 0.5
  image_features: ${model.net.features}

text_embed_net:
  _target_: src.models.components.text_embedding.Glove_LSTM
  embed_dim: 200
  drop_rate: 0.5
  text_features: ${model.net.features}
  n_layer_lstm: 1
  dataset_dir: ${model.dataset_dir}

features: 256
dataset_dir: ${model.dataset_dir}
