_target_: src.models.components.ImageCaptionNet
image_embed_net:
  _target_: src.models.components.image_embedding.InceptionNet
  drop_rate: 0.5
  image_features: ${model.net.features}

text_embed_net:
  _target_: src.models.components.text_embedding.Bert
  drop_rate: 0.5
  text_features: ${model.net.features}

features: 256
dataset_dir: ${model.dataset_dir}
